service: youtube-dl-extract-info
frameworkVersion: '3'

resources:
  Description: YouTube-dl as an API

package:
  individually: true

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  timeout: 30
  apiName: ${self:service}-${self:provider.stage}

functions:
  youtube-dl-extract-info:
    name: ${self:service}-${self:provider.stage}
    description: Youtube-dl extract info based on URL
    handler: extract_info.lambda_handler
    events:
      - http:
          path: extract-info
          method: get
          request:
            parameters:
              querystrings:
                url: true
    package:
      patterns:
        - '!**' 
        - 'extract_info.py'
        - 'youtube_dl/**'
